# Generated by Django 5.0.7 on 2024-07-15 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Movie',
        ),
    ]
