# Generated by Django 5.0.7 on 2024-07-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_movie_trailer_link_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_link',
            field=models.URLField(null=True, verbose_name='Link para o trailer'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='watch_links',
            field=models.URLField(null=True, verbose_name='Links para Assistir'),
        ),
    ]
