# Generated by Django 5.0.7 on 2024-07-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_movie_watch_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='watch_links',
            field=models.TextField(blank=True, null=True, verbose_name='Links para Assistir'),
        ),
    ]
