# Generated by Django 5.0.7 on 2024-07-16 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rate_created_at_alter_comment_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
